#!/bin/bash

# Check if namespace is provided
if [ -z "$1" ]; then
  echo "Usage: $0 <namespace>"
  exit 1
fi

N="$1"

echo "----------------------------------------------------------------------------------------------"
echo "Namespace: $N"
echo "----------------------------------------------------------------------------------------------"
echo "### DEPLOYMENT ###"
kubectl -n "$N" get deploy -o wide
for d in $(kubectl -n cri get deploy --no-headers | awk '{print $1}'); do   kubectl -n cri describe deploy "$d" | grep Selector:; done
for d in $(kubectl -n cri get deploy --no-headers | awk '{print $1}'); do   kubectl -n cri describe deploy "$d" | grep Replicas:; done
echo "### SERVICE ###"
kubectl -n "$N" get svc -o wide | grep "NodePort"
echo "### REPLICA SETS ###"
kubectl -n "$N" get rs -o wide
echo "### HORIZONTAL POD AUTO-SCALE ###"
kubectl -n "$N" get hpa
echo "### RUNNING AND READY PODS ###"
kubectl -n "$N" get pods -o wide | grep "1/1" | grep -v "Terminating"
echo "### TO BE READY SOON / FAILED PODS ###"
kubectl -n "$N" get pods -o wide | grep "0/1"
echo "### TERMINATING PODS  ###"
kubectl -n "$N" get pods -o wide | grep "Terminating"
echo "### DEPLOYED PODS RESOURCES ###"
kubectl -n "$N" top pods --sum
echo "### NODES ###"
kubectl get nodes -o wide
echo "### NODE RESOURCE ###"
kubectl top node
echo "----------------------------------------------------------------------------------------------"

