#!/bin/bash

# Check if namespace is provided
if [ -z "$1" ]; then
  echo "Usage: $0 <namespace>"
  exit 1
fi

N="$1"

echo "----------------------------------------------------------------------------------------------------------------------------"
echo "Namespace: $N"
echo "----------------------------------------------------------------------------------------------------------------------------"
echo "### DEPLOYMENT ###"
kubectl -n "$N" get deploy -o wide
for d in $(kubectl -n "$N" get deploy --no-headers | awk '{print $1}'); do   kubectl -n cri describe deploy "$d" | grep Selector:; done
for d in $(kubectl -n "$N" get deploy --no-headers | awk '{print $1}'); do   kubectl -n cri describe deploy "$d" | grep Replicas:; done
echo "### SERVICE ###"
kubectl -n "$N" get svc -o wide | grep "NodePort"
echo "### REPLICA SETS ###"
kubectl -n "$N" get rs -o wide
echo "### HORIZONTAL POD AUTO-SCALE ###"
kubectl -n "$N" get hpa
echo "### RUNNING AND READY PODS IN [NODE-1] ###"
kubectl -n "$N" get pods -o wide --no-headers \
| awk '!/Terminating/ && /node-1/ {print NR, $0}'
echo "### RUNNING AND READY PODS IN [NODE-2] ###"
kubectl -n "$N" get pods -o wide --no-headers \
| awk '!/Terminating/ && /node-2/ {print NR, $0}'
echo "### RUNNING AND READY PODS IN [NODE-3] ###"
kubectl -n "$N" get pods -o wide --no-headers \
| awk '!/Terminating/ && /node-3/ {print NR, $0}'
echo "### TO BE READY SOON / FAILED PODS ###"
kubectl -n "$N" get pods -o wide | grep "0/1"
echo "### TERMINATING PODS  ###"
kubectl -n "$N" get pods -o wide | grep "Terminating"
echo "### DEPLOYED PODS RESOURCES ###"
kubectl -n "$N" top pods --sum
echo "### NODES ###"
kubectl get nodes -o wide
echo "### NODE RESOURCE ###"
kubectl top node
echo "---------------------------------------------------------------------------------------------------------------------------"

# MODIFICATION TO BE DOWN BEFORE USE !!
# NODE NAME NEEDS TO BE REPLACED ACCORDING TO YOUR <NODE NAME>
